var a2 = new Audio();
a2.src = "./audio/a2.wav"
var a3 = new Audio();
a3.src = "./audio/a3.wav"
var a4 = new Audio();
a4.src = "./audio/a4.wav"
var a5 = new Audio();
a5.src = "./audio/a5.wav"
var a6 = new Audio();
a6.src = "./audio/a6.wav"
var a7 = new Audio();
a7.src = "./audio/a7.wav"
var b2 = new Audio();
b2.src = "./audio/b2.wav"
var b3 = new Audio();
b3.src = "./audio/b3.wav"
var b4 = new Audio();
b4.src = "./audio/b4.wav"
var b5 = new Audio();
b5.src = "./audio/b5.wav"
var b6 = new Audio();
b6.src = "./audio/b6.wav"
var b7 = new Audio();
b7.src = "./audio/b7.wav"
var c2 = new Audio();
c2.src = "./audio/c2.wav"
var c3 = new Audio();
c3.src = "./audio/c3.wav"
var c4 = new Audio();
c4.src = "./audio/c4.wav"
var c5 = new Audio();
c5.src = "./audio/c5.wav"
var c6 = new Audio();
c6.src = "./audio/c6.wav"
var c7 = new Audio();
c7.src = "./audio/c7.wav"
var wpp = new Audio();
wpp.src = "./audio/wpp.mp3"
